version: "3.7"

services:
    algorithms-rust-dev:
        build:
            context: ..
            dockerfile: ./.docker/Dockerfile
        volumes:
            - ..:/home/docker-user/workspace
        cap_add:
            - SYS_PTRACE
        command: sleep infinity
